// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: pb/tzinfo.compress.proto

package pb

import (
	slimarray "github.com/openacid/slimarray"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompressPolygon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LngSlimArray *slimarray.SlimArray `protobuf:"bytes,1,opt,name=LngSlimArray,proto3" json:"LngSlimArray,omitempty"`
	LatSlimArray *slimarray.SlimArray `protobuf:"bytes,2,opt,name=LatSlimArray,proto3" json:"LatSlimArray,omitempty"`
}

func (x *CompressPolygon) Reset() {
	*x = CompressPolygon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_tzinfo_compress_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompressPolygon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressPolygon) ProtoMessage() {}

func (x *CompressPolygon) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tzinfo_compress_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressPolygon.ProtoReflect.Descriptor instead.
func (*CompressPolygon) Descriptor() ([]byte, []int) {
	return file_pb_tzinfo_compress_proto_rawDescGZIP(), []int{0}
}

func (x *CompressPolygon) GetLngSlimArray() *slimarray.SlimArray {
	if x != nil {
		return x.LngSlimArray
	}
	return nil
}

func (x *CompressPolygon) GetLatSlimArray() *slimarray.SlimArray {
	if x != nil {
		return x.LatSlimArray
	}
	return nil
}

type CompressTimezone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompressPolygons []*CompressPolygon `protobuf:"bytes,1,rep,name=compressPolygons,proto3" json:"compressPolygons,omitempty"`
	Name             string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CompressTimezone) Reset() {
	*x = CompressTimezone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_tzinfo_compress_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompressTimezone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressTimezone) ProtoMessage() {}

func (x *CompressTimezone) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tzinfo_compress_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressTimezone.ProtoReflect.Descriptor instead.
func (*CompressTimezone) Descriptor() ([]byte, []int) {
	return file_pb_tzinfo_compress_proto_rawDescGZIP(), []int{1}
}

func (x *CompressTimezone) GetCompressPolygons() []*CompressPolygon {
	if x != nil {
		return x.CompressPolygons
	}
	return nil
}

func (x *CompressTimezone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CompressTimezones struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompressTimezones []*CompressTimezone `protobuf:"bytes,1,rep,name=compressTimezones,proto3" json:"compressTimezones,omitempty"`
	Precise           int32               `protobuf:"varint,2,opt,name=precise,proto3" json:"precise,omitempty"`
}

func (x *CompressTimezones) Reset() {
	*x = CompressTimezones{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_tzinfo_compress_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompressTimezones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressTimezones) ProtoMessage() {}

func (x *CompressTimezones) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tzinfo_compress_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressTimezones.ProtoReflect.Descriptor instead.
func (*CompressTimezones) Descriptor() ([]byte, []int) {
	return file_pb_tzinfo_compress_proto_rawDescGZIP(), []int{2}
}

func (x *CompressTimezones) GetCompressTimezones() []*CompressTimezone {
	if x != nil {
		return x.CompressTimezones
	}
	return nil
}

func (x *CompressTimezones) GetPrecise() int32 {
	if x != nil {
		return x.Precise
	}
	return 0
}

var File_pb_tzinfo_compress_proto protoreflect.FileDescriptor

var file_pb_tzinfo_compress_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x62, 0x2f, 0x74, 0x7a, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x19,
	0x73, 0x6c, 0x69, 0x6d, 0x61, 0x72, 0x72, 0x61, 0x79, 0x2f, 0x73, 0x6c, 0x69, 0x6d, 0x61, 0x72,
	0x72, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x0f, 0x43, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x38, 0x0a,
	0x0c, 0x4c, 0x6e, 0x67, 0x53, 0x6c, 0x69, 0x6d, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x6c, 0x69, 0x6d, 0x61, 0x72, 0x72, 0x61, 0x79, 0x2e,
	0x53, 0x6c, 0x69, 0x6d, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x0c, 0x4c, 0x6e, 0x67, 0x53, 0x6c,
	0x69, 0x6d, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x38, 0x0a, 0x0c, 0x4c, 0x61, 0x74, 0x53, 0x6c,
	0x69, 0x6d, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x73, 0x6c, 0x69, 0x6d, 0x61, 0x72, 0x72, 0x61, 0x79, 0x2e, 0x53, 0x6c, 0x69, 0x6d, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x52, 0x0c, 0x4c, 0x61, 0x74, 0x53, 0x6c, 0x69, 0x6d, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x22, 0x67, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6f, 0x6e, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x71, 0x0a, 0x11, 0x43, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65, 0x73, 0x12,
	0x42, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x7a,
	0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x7a, 0x6f, 0x6e, 0x65,
	0x52, 0x11, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x7a, 0x6f,
	0x6e, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x65, 0x42, 0x21, 0x5a,
	0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x69, 0x6e, 0x67,
	0x73, 0x61, 0x74, 0x75, 0x72, 0x6e, 0x2f, 0x74, 0x7a, 0x66, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_tzinfo_compress_proto_rawDescOnce sync.Once
	file_pb_tzinfo_compress_proto_rawDescData = file_pb_tzinfo_compress_proto_rawDesc
)

func file_pb_tzinfo_compress_proto_rawDescGZIP() []byte {
	file_pb_tzinfo_compress_proto_rawDescOnce.Do(func() {
		file_pb_tzinfo_compress_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_tzinfo_compress_proto_rawDescData)
	})
	return file_pb_tzinfo_compress_proto_rawDescData
}

var file_pb_tzinfo_compress_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_tzinfo_compress_proto_goTypes = []interface{}{
	(*CompressPolygon)(nil),     // 0: pb.CompressPolygon
	(*CompressTimezone)(nil),    // 1: pb.CompressTimezone
	(*CompressTimezones)(nil),   // 2: pb.CompressTimezones
	(*slimarray.SlimArray)(nil), // 3: slimarray.SlimArray
}
var file_pb_tzinfo_compress_proto_depIdxs = []int32{
	3, // 0: pb.CompressPolygon.LngSlimArray:type_name -> slimarray.SlimArray
	3, // 1: pb.CompressPolygon.LatSlimArray:type_name -> slimarray.SlimArray
	0, // 2: pb.CompressTimezone.compressPolygons:type_name -> pb.CompressPolygon
	1, // 3: pb.CompressTimezones.compressTimezones:type_name -> pb.CompressTimezone
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_tzinfo_compress_proto_init() }
func file_pb_tzinfo_compress_proto_init() {
	if File_pb_tzinfo_compress_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_tzinfo_compress_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompressPolygon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_tzinfo_compress_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompressTimezone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_tzinfo_compress_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompressTimezones); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_tzinfo_compress_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_tzinfo_compress_proto_goTypes,
		DependencyIndexes: file_pb_tzinfo_compress_proto_depIdxs,
		MessageInfos:      file_pb_tzinfo_compress_proto_msgTypes,
	}.Build()
	File_pb_tzinfo_compress_proto = out.File
	file_pb_tzinfo_compress_proto_rawDesc = nil
	file_pb_tzinfo_compress_proto_goTypes = nil
	file_pb_tzinfo_compress_proto_depIdxs = nil
}
