name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  deployments: write

jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          pr_comment: true
          breaking: true
          breaking_against: "https://github.com/ringsaturn/tzf.git#branch=main"


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - run: ls -al

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout=5m
          skip-cache: true

      - name: Run coverage
        run: go test -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6

      - name: Bench
        run: make bench

      - name: Memory footprint
        run: make bench-memory


      - name: Write benchmark summary
        run: python3 scripts/bench2summary.py benchmark_result.txt memory_result.txt >> $GITHUB_STEP_SUMMARY
